services:
  ai:
    image: ai-agents:v1
    ports:
      - 5000:8080
    restart: always
  redis:
    image: redis
    restart: always
    command: redis-server --save 3600 1
    volumes:
      - ./cache:/data
    environment:
      - "TZ=America/Sao_Paulo"
    ports:
      - 9999:6379
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"